---
title: "88milSMS"
author: "Twixer"
date: "Friday, September 26, 2014"
output: 
    html_document :
        toc: true
        theme: united
    md_document :
        fig_retina: true
---

``` {r global_options, echo=F}
library(knitr,quietly = T)
library(xtable, quietly = T)

opts_chunk$set(echo= TRUE, 
               results='asis',
               cache=T,
               cache.path="cache/",
               fig.path="figures/")


# trick : http://stackoverflow.com/questions/8652674/r-xtable-and-dates
xtable <- function(x, ...) {
   for (i in which(sapply(x, function(y) !all(is.na(match(c("POSIXt","Date"),class(y))))))) x[[i]] <- as.character(x[[i]])
   xtable::xtable(x, ...)
}

source("scripts/get_clean_save_dataframe.R")
```

# Introduction
This project is an R analysis of the 88milSMS project.
The initial project is hosted at http://88milsms.huma-num.fr/index.html.

# Data


```{r view_data }
data <- load.data()

xt <- xtable(data)
print(head(xt), type="html")

```

# License

## Data

The license about the terms of use for the data is described at http://88milsms.huma-num.fr/corpus.html. 

An R analysis of the 88milSMS project.
The initial project is hosted at http://88milsms.huma-num.fr/index.html.

The license about the term of use for the data is described at http://88milsms.huma-num.fr/corpus.html. 
